section:
  description: app settings
  loadFrom: [ buildinfo.yaml, configuration/settings.json ]
loggingConfiguration:
  mainLogger:
    name: game
    rotationLogger:
      logFileName: "logs/engine.log"
      maximumFileSize: 5242880
      maximumFilesCount: 3
    stdoutLogger: {}
localizations:
  english:
    - configuration/localization/english.yaml
  german:
    - configuration/localization/german.yaml
userInterface:
  section:
    description: user interface settings
    loadFrom: [ configuration/interface.user.yaml ]
    saveTo: configuration/interface.user.yaml
  activeLanguage: german
fileSystemWatches:
  - directory: "./"
    recursive: true
extensions:
  #- name: "OpenglRenderer"
  #  path: "modules/renderer-opengl"
  #  reloadOnModification: true
  #  modules:
  #    - "renderer-opengl"
  - name: "TestExtension"
    path: "modules/test-extension"
    reloadOnModification: true
    modules:
      - "test-extension"
assetTypes:
  extension: ".(so|dll)$"
  openglFragmentShader: ".frag$"
  openglVertexShader: ".vert$"