overrideWithFiles:
  - configuration/settings.yaml
loggingConfiguration:
  mainLogger:
    name: engine
    rotationLogger:
      logFileName: "logs/engine.log"
      maximumFileSize: 5242880
      maximumFilesCount: 3
    stdoutLogger: {}
localizations:
  english:
    - configuration/strings.en.txt
    - configuration/strings2.en.txt
  french:
    - configuration/strings.fr.txt
    - configuration/strings2.fr.txt
interface:
  overrideWithFiles:
    - configuration/interface.user.yaml
  activeLanguage: english