settingFiles:
  - configuration/settings.yaml
loggingConfiguration:
  mainLogger:
    name: engine
    rotationLogger:
      logFileName: "logs/engine.log"
      maximumFileSize: 5242880
      maximumFilesCount: 3
    stdoutLogger: {}
i18nSets:
  English:
    - configuration/strings.en.txt
    - configuration/strings2.en.txt
  French:
    - configuration/strings.fr.txt
    - configuration/strings2.fr.txt
activeI18nSet: English