section:
  description: app settings
  loadFrom: [ configuration/settings.json ]
loggingConfiguration:
  mainLogger:
    name: engine
    rotationLogger:
      logFileName: "logs/engine.log"
      maximumFileSize: 5242880
      maximumFilesCount: 3
    stdoutLogger: {}
localizations:
  english:
    - configuration/localization/english.yaml
  german:
    - configuration/localization/german.yaml
interface:
  section:
    description: user interface settings
    loadFrom: [ configuration/interface.user.yaml ]
    saveTo: configuration/interface.user.yaml
  activeLanguage: english