section:
  description: app settings
  loadFrom: [ configuration/settings.json ]
  saveTo: configuration/settings.user.json
loggingConfiguration:
  mainLogger:
    name: engine
    rotationLogger:
      logFileName: "logs/engine.log"
      maximumFileSize: 5242880
      maximumFilesCount: 3
    stdoutLogger: {}
localizations:
  english:
    - configuration/strings.en.txt
    - configuration/strings2.en.txt
  french:
    - configuration/strings.fr.txt
    - configuration/strings2.fr.txt
interface:
  section:
    description: user interface settings
    loadFrom: [ configuration/interface.user.yaml ]
    saveTo: configuration/interface.user.yaml
  activeLanguage: english