name: root
pipeline:
  nodes:
    view-update:
      parent: post-update
      trigger:
        type: TimeFrameTrigger
        milliseconds: 16.0
      controller:
        type: ViewController
    animation-update:
      trigger:
        type: TimeFrameTrigger
        milliseconds: 33.33