name: root
pipeline:
  nodes:
    events:
      controller: EventDispatcher
    #profiler:
    #  controller: Profiler
    update:
      trigger:
        type: TimeFrameTrigger
        duration:
          milliseconds: 33.333333333
      children:
        accelerate-objects:
          controller: AccelerationMovementController
        move-objects:
          controller: MovementController
        transform-objects:
          controller: TransformController
        make-state-snapshot:
          controller: StateUpdater
    render-views:
      controller: ViewController
      children:
        output-fps:
          controllerInstance:
            type: FrameCounter
            interval:
              seconds: 1.0
    flush-console:
      controller: ConsoleFlusher
    pump-window-events:
      controller: WindowSystemController
directors:
  - type: ConfigurationLoader
  - type: AssetLoader