name: root
pipeline:
  nodes:
    profiler:
      parent: pre-update
      #controller:
      #  type: Profiler
    view-update:
      parent: post-update
      controller:
        type: ViewController
      children:
        fps:
          controller:
            type: FrameCounter
            interval:
              seconds: 1.0
    animation-update:
      trigger:
        type: TimeFrameTrigger
        duration:
          milliseconds: 33.33