name: root
pipeline:
  nodes:
    events:
      parent: pre-update
      controller:
        type: EventDispatcher
    #profiler:
    #  parent: pre-update
    #  controller:
    #    type: Profiler
    update:
      parent: update
      trigger:
        type: TimeFrameTrigger
        duration:
          milliseconds: 33.333333333
      children:
        accelerator:
          controller:
            type: AccelerationMovementController
        movement:
          controller:
            type: MovementController
        transform:
          controller:
            type: TransformController
        state:
          controller:
            type: StateUpdater
    view:
      parent: post-update
      controller:
        type: ViewController
      children:
        fps:
          controller:
            type: FrameCounter
            interval:
              seconds: 1.0
    console-flush:
      parent: post-update
      controller:
        type: ConsoleFlusher