name: root
pipeline:
  nodes:
    events:
      controller:
        type: EventDispatcher
    #profiler:
    #  controller:
    #    type: Profiler
    update:
      trigger:
        type: TimeFrameTrigger
        duration:
          milliseconds: 33.333333333
      children:
        accelerator:
          controller:
            type: AccelerationMovementController
        movement:
          controller:
            type: MovementController
        transform:
          controller:
            type: TransformController
        state:
          controller:
            type: StateUpdater
    view:
      controller:
        type: ViewController
      children:
        fps:
          controller:
            type: FrameCounter
            interval:
              seconds: 1.0
    console-flush:
      controller:
        type: ConsoleFlusher
    pump-window-events:
      controller:
        type: WindowSystemController