name: root
devices:
  - type: StandardIODevice
  - type: TerminalDevice
  #- type: GlfwDisplaySystemDevice
  #- type: GlfwWindowSystemDevice
  #- type: FileWatcherDevice
  - type: OpenglGpuDevice
  #- type: ImageStreamDevice
pipeline:
  nodes:
    events:
      controller: EventDispatcher
    #profiler:
    #  controller: Profiler
    update:
      trigger:
        type: TimeFrameTrigger
        duration:
          milliseconds: 33.333333333
      children:
        accelerate-objects:
          controller: AccelerationMovementController
        move-objects:
          controller: MovementController
        transform-objects:
          controller: TransformController
        make-state-snapshot:
          controller: StateUpdater
    render-views:
      controller: ViewController
      children:
        output-fps:
          controllerInstance:
            type: FrameCounter
            interval:
              seconds: 1.0
    flush-console:
      controller: ConsoleFlusher
    pump-window-events:
      controller: WindowSystemController
directors:
  - type: ApplicationDirector #attach controlling event logic(control display layout creating, resizing and deletion)
  - type: FlushEventBuffers #process device events(here display layouts will be created)
  - type: ViewDirector
  - type: AssetLoader
  - type: LoadScene #load the window layout scene and attach its layout to the available display layouts
    filename: $windowLayoutScene


