#pragma once

#include "dependencies.h"
#include "basicFrameService.h"
#include "controllers/inputController.h"
#include "multithreading/individualProcessThread.h"
#include "devices/consoleSystem.h"
#include "devices/windowSystem.h"
#include "devices/windowParameters.h"
#include "messaging/event.h"
#include "messaging/eventHub.h"
#include "messaging/events/systemConsole/systemConsoleEventHub.h"
#include "messaging/events/systemWindow/systemWindowEventHub.h"
#include "domain/view.h"
#include "domain/geometry/transformation.h"
#include "domain/geometry/transformationFactory.h"