#pragma once

#include "dependencies.h"
#include "configuration/configuration.h"
#include "configuration/fileSystemBasedConfiguration.h"
#include "basicFrameService.h"
#include "controllers/inputController.h"
#include "controllers/viewController.h"
#include "multithreading/individualProcessThread.h"
#include "devices/consoleSystem.h"
#include "messaging/eventHub.h"
#include "messaging/events/systemConsole/systemConsoleEventHub.h"
#include "domain/geometry/transformation.h"
#include "domain/geometry/matrixCalculator.h"
#include "domain/geometry/transformationCalculator.h"
#include "domain/geometry/mathFunctions.h"
#include "domain/repositories/viewEntityRepository.h"